blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.index, name='index'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

blogicum/blogicum/users/urls.py
# users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    # Вход/выход
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    
    # Регистрация
    path('signup/', views.SignUpView.as_view(), name='signup'),
    
    # Профиль
    path('profile/<str:username>/', views.ProfileDetailView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    
    # Изменение пароля
    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
    
    # Встроенные представления Django для сброса пароля
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            subject_template_name='users/password_reset_subject.txt',
            success_url='/auth/password_reset/done/'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/auth/reset/done/'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

blogicum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

blogicum/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.registration, name='registration'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name='profile'),
    path('profile/<str:username>/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
]

blogicum/users/models.py
from django.db import models

# Create your models here.

blogicum/blogicum/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254,
        required=True,
        help_text='Обязательное поле. Введите действующий email.',
        label='Адрес электронной почты'
    )
    first_name = forms.CharField(
        max_length=150,
        required=False,
        label='Имя'
    )
    last_name = forms.CharField(
        max_length=150,
        required=False,
        label='Фамилия'
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Пользователь с таким email уже существует.')
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError('Пользователь с таким именем уже существует.')
        return username


class ProfileUpdateForm(forms.ModelForm):
    """Форма для обновления профиля пользователя."""
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }

blogicum/blogicum/users/views.py
# blogicum/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.models import User

from .forms import CustomUserCreationForm


class CustomLoginView(LoginView):
    """Кастомный вход пользователя."""
    template_name = 'users/login.html'
    redirect_authenticated_user = True


class CustomLogoutView(LogoutView):
    """Кастомный выход пользователя."""
    template_name = 'users/logged_out.html'


class SignUpView(CreateView):
    """Регистрация нового пользователя."""
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('blog:index')
    template_name = 'users/signup.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request,
            'Вы успешно зарегистрировались! Теперь вы можете войти.'
        )
        return response


class ProfileDetailView(DetailView):
    """Просмотр профиля пользователя."""
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'profile_user'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем публикации пользователя (пример из блога)
        from blog.models import Post  # Импортируем здесь, чтобы избежать циклического импорта
        context['user_posts'] = Post.objects.filter(
            author=self.object
        ).order_by('-created_at')[:10]
        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование профиля пользователя."""
    model = User
    template_name = 'users/profile_edit.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    success_url = reverse_lazy('users:profile_edit')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Профиль успешно обновлен!')
        return super().form_valid(form)


@login_required
def password_change(request):
    """Изменение пароля пользователя."""
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Ваш пароль был успешно изменен!')
            return redirect('users:profile', username=request.user.username)
    else:
        form = PasswordChangeForm(request.user)
    
    return render(request, 'users/password_change.html', {'form': form})


@login_required
def password_change_done(request):
    """Страница успешного изменения пароля."""
    return render(request, 'users/password_change_done.html')

blogicum/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import UpdateView
from .forms import CustomUserCreationForm, ProfileUpdateForm
from ice_cream.models import IceCream  # предположим, что у вас есть модель IceCream
from django.core.paginator import Paginator


def registration(request):
    """Регистрация нового пользователя"""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage:index')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'users/registration.html', {'form': form})


class UserProfileView(DetailView):
    """Страница профиля пользователя"""
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'profile_user'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        
        # Получаем публикации пользователя с пагинацией
        posts = IceCream.objects.filter(
            is_published=True,
            owner=user
        ).order_by('-created_at')
        
        paginator = Paginator(posts, 10)  # 10 постов на страницу
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['page_obj'] = page_obj
        context['is_owner'] = self.request.user == user
        return context


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Редактирование профиля"""
    model = User
    form_class = ProfileUpdateForm
    template_name = 'users/profile_edit.html'
    
    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'username': self.object.username})
    
    def test_func(self):
        user = self.get_object()
        return self.request.user == user

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import UpdateView
from .forms import CustomUserCreationForm, ProfileUpdateForm
from ice_cream.models import IceCream
from django.core.paginator import Paginator


def registration(request):
    """Регистрация нового пользователя"""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage:index')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'users/registration.html', {'form': form})


class UserProfileView(DetailView):
    """Страница профиля пользователя"""
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'profile_user'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        
        # Получаем публикации пользователя с пагинацией
        posts = IceCream.objects.filter(
            is_published=True,
            owner=user
        ).order_by('-created_at')
        
        paginator = Paginator(posts, 10)  # 10 постов на страницу
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['page_obj'] = page_obj
        context['is_owner'] = self.request.user == user
        return context


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Редактирование профиля"""
    model = User
    form_class = ProfileUpdateForm
    template_name = 'users/profile_edit.html'
    
    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'username': self.object.username})
    
    def test_func(self):
        user = self.get_object()
        return self.request.user == user

templates/users/profile.html
{% extends "base.html" %}

{% block title %}Профиль {{ profile_user.username }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h5>Информация о пользователе</h5>
                </div>
                <div class="card-body">
                    <p><strong>Логин:</strong> {{ profile_user.username }}</p>
                    <p><strong>Имя:</strong> {{ profile_user.first_name|default:"Не указано" }}</p>
                    <p><strong>Фамилия:</strong> {{ profile_user.last_name|default:"Не указана" }}</p>
                    <p><strong>Email:</strong> {{ profile_user.email|default:"Не указан" }}</p>
                    <p><strong>Дата регистрации:</strong> {{ profile_user.date_joined|date:"d.m.Y" }}</p>
                    
                    {% if is_owner %}
                        <hr>
                        <div class="d-grid gap-2">
                            <a href="{% url 'users:profile_edit' %}" class="btn btn-primary">
                                Редактировать профиль
                            </a>
                            <a href="{% url 'users:password_change' %}" class="btn btn-warning">
                                Изменить пароль
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Публикации пользователя</h5>
                    <span class="badge bg-secondary">{{ posts.paginator.count }} постов</span>
                </div>
                <div class="card-body">
                    {% if posts %}
                        {% for post in posts %}
                            <div class="card mb-2">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}" style="height: 200px; object-fit: cover;">
                                {% endif %}
                                <div class="card-body">
                                    <h6>
                                        <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                                        {% if not post.is_published %}
                                            <span class="badge bg-warning">Черновик</span>
                                        {% endif %}
                                        {% if post.pub_date > timezone.now %}
                                            <span class="badge bg-info">Отложен</span>
                                        {% endif %}
                                    </h6>
                                    <p class="card-text">{{ post.text|truncatewords:20 }}</p>
                                    <div class="d-flex justify-content-between">
                                        <small class="text-muted">
                                            {{ post.pub_date|date:"d.m.Y H:i" }}
                                            {% if post.category %}
                                                | {{ post.category.title }}
                                            {% endif %}
                                        </small>
                                        <small class="text-muted">
                                            {{ post.comments.count }} комментариев
                                        </small>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        
                        <!-- Пагинация -->
                        {% if posts.has_other_pages %}
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">
                                    {% if posts.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    
                                    {% for i in posts.paginator.page_range %}
                                        {% if posts.number == i %}
                                            <li class="page-item active">
                                                <span class="page-link">{{ i }}</span>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    
                                    {% if posts.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    {% else %}
                        <p class="text-center text-muted">У пользователя пока нет публикаций</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}